# -*- coding: utf-8 -*-
"""a3_q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VxBXmBAYm77Pirs8ndBNad9eRjAzAH5x
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
import sklearn
!pip3 install idx2numpy
import idx2numpy
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

arr_img = idx2numpy.convert_from_file('/content/train-images.idx3-ubyte')
arr_labels = idx2numpy.convert_from_file('/content/train-labels.idx1-ubyte')
arr_img= np.reshape(arr_img,(60000, 784))

pca_15 = PCA(n_components=15)
pca_15.fit(arr_img)

arr1 = pca_15.transform(arr_img)
print(len(arr1[0]))

clf = LDA()
clf.fit(arr1, arr_labels)

arr_img_test = idx2numpy.convert_from_file('/content/t10k-images.idx3-ubyte')
arr_labels_test = idx2numpy.convert_from_file('/content/t10k-labels.idx1-ubyte')
arr_img_test = np.reshape(arr_img_test, (10000, 784))

arr_test = pca_15.transform(arr_img_test)
pred = clf.predict(arr_test)

correct =0
incorrect=0
for i in range(len(pred)):
  if (pred[i] == arr_labels_test[i]):
    correct+=1
  else:
    incorrect+=1
acc_15 = correct*100/(correct+incorrect)
print("Accuracy = "+ str(correct*100/(correct+incorrect)))

pca_8 = PCA(n_components = 8)
pca_8.fit(arr_img)

arr1 = pca_8.transform(arr_img)
clf.fit(arr1, arr_labels)
arr_test = pca_8.transform(arr_img_test)
pred = clf.predict(arr_test)
correct =0
incorrect=0
for i in range(len(pred)):
  if (pred[i] == arr_labels_test[i]):
    correct+=1
  else:
    incorrect+=1
acc_8=correct*100/(correct+incorrect)
print("Accuracy = "+ str(correct*100/(correct+incorrect)))

pca_3 = PCA(n_components = 3)
pca_3.fit(arr_img)

arr1 = pca_3.transform(arr_img)
clf.fit(arr1, arr_labels)
arr_test = pca_3.transform(arr_img_test)
pred = clf.predict(arr_test)
correct =0
incorrect=0
for i in range(len(pred)):
  if (pred[i] == arr_labels_test[i]):
    correct+=1
  else:
    incorrect+=1
acc_3 = correct*100/(correct+incorrect)
print("Accuracy = "+ str(correct*100/(correct+incorrect)))

x_axis = [3,8,15]
y_axis = [acc_3, acc_8, acc_15]
plt.plot(x_axis, y_axis)
plt.show()